# Theme settings
dox:
  baseurl: https://keyconnect.app
  title: KeyConnect
  theme_color: "#0047FF" # Define theme primary color with HEX value
  language: en-GB # Use ISO language and country codes to setup language of your website - https://www.w3schools.com/tags/ref_language_codes.asp and https://www.w3schools.com/tags/ref_country_codes.asp
  header:
    logo:
      text: #
      image: logo.png
    nav:
      - item_name: API Docs
        item_url: https://www.keyconnect.app/api-docs/index.html
      - item_name: Server
        item_url: /server
    cta:
      label: SDK
      url: /documentation/java-sdk
      external_url: false
      icon: book-open
  footer:
    logo:
      text: Key Connect
      image:
    text: Copyright &copy; 2021. - Key Connect <br>All rights reserved.
  google_analytics:
    tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
  comments:
    disqus_forum_shortname: # Add your Disqus forum shortname to activate comments site-wide

# Defining collections
collections:
  documentation:
    output: true

# Defining defaults
defaults:
  - scope:
      path: ""
      type: "documentation"
    values:
      layout: "documentation-single"

# SASS settings
sass:
  sass_dir: ./theme/_sass
  style: :compressed

# Jekyll settings
layouts_dir: ./theme/_layouts
includes_dir: ./theme/_includes
exclude: ["README.md", "CHANGELOG.md", "vendor"]
permalink: /:title/
